In [1]:
import numpy


In [2]:
import numpy as np


In [3]:
print(np.__version__)

2.1.1


In [4]:
len(dir(np))

535

In [5]:
l=[2,3,34,5,5,"Ram"]


In [6]:
arr=np.array(1)
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr.dtype

dtype('int64')

In [8]:
a=np.array([1,2,3,4,5])
a.dtype

dtype('int64')

In [12]:
a=np.array([1,2,3,4,255],dtype="uint8")
a.dtype

dtype('uint8')

In [17]:
a=np.arange(1,8)
print(a)

[1 2 3 4 5 6 7]


In [20]:
a=np.arange(1,12)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [21]:
a.ndim

1

In [22]:
a=np.arange(1,13).reshape(3,4)
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
a.ndim


2

In [24]:
a=np.arange(1,13).reshape(3,2,2)
a


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [25]:
a.shape

(3, 2, 2)

In [29]:
ones1=np.ones(12)
ones1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
ones1=np.ones(12,dtype="str")
ones1

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
      dtype='<U1')

In [33]:
zeros=np.zeros(14)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
a=np.random.randint(1,100(2,4))
a

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\ftt\AppData\Local\Temp\ipykernel_12544\438890501.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  a=np.random.randint(1,100(2,4))
C:\Users\ftt\AppData\Local\Temp\ipykernel_12544\438890501.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  a=np.random.randint(1,100(2,4))
C:\Users\ftt\AppData\Local\Temp\ipykernel_12544\438890501.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  a=np.random.randint(1,100(2,4))
C:\Users\ftt\AppData\Local\Temp\ipykernel_12544\438890501.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  a=np.random.randint(1,100(2,4))


TypeError: 'int' object is not callable

In [41]:
a=np.arange(1,11)
b=np.arange(100,110)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[100 101 102 103 104 105 106 107 108 109]


In [43]:
a=np.random.randint(1,1000,20)
a

array([513, 152, 455,  99, 593, 651, 924, 672, 679, 901, 171, 539, 151,
       375, 816, 204, 388, 994, 624, 477], dtype=int32)

In [44]:
e=a[a<500]
e

array([152, 455,  99, 171, 151, 375, 204, 388, 477], dtype=int32)

In [46]:
e=a[(a<500) & (a%11==0)]
e

array([99], dtype=int32)

In [55]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(100,112).reshape(4,3)
print("a=" ,a)

print("b=",b)

a= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b= [[100 101 102]
 [103 104 105]
 [106 107 108]
 [109 110 111]]


In [56]:
a.mean()

np.float64(6.5)

In [57]:
a.std()

np.float64(3.452052529534663)

In [58]:
np.min(a)

np.int64(1)

In [59]:
np.argmin(a)

np.int64(0)

In [60]:
np.max(a)

np.int64(12)

In [61]:
np.max(b)

np.int64(111)

In [62]:
c=a.reshape(12)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
a1=a.flatten() #####BY using flatten we can convert any matrix into one dimensional array.
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
df=np.read_csv("D:\\test_scores-checkpoint")

NameError: name 'np' is not defined

In [11]:
import pandas as pd

In [15]:
df=pd.read_csv("D:\test_scores-checkpoint")

OSError: [Errno 22] Invalid argument: 'D:\test_scores-checkpoint'